---
- hosts: my_servers
  become: true
  tasks:
    - name: Print OS information
      debug:
        msg: "Operating System: {{ ansible_distribution }} {{ ansible_distribution_version }}"

    - name: Install Apache web server
      ansible.builtin.package:
        name: apache2
        state: present
