---
- name: Update web servers
  hosts: proxmox_servers

  tasks:
  - name: Install Python3-pip
    ansible.builtin.apt:
      name: python3-pip
      state: present
  - name: Install setuptools modules via pip
    ansible.builtin.pip:
      name: setuptools
      state: present
  - name: Install requests module via pip
    ansible.builtin.pip:
      name: requests
      state: present
  - name: install proxmoxer module via pip
    ansible.builtin.pip:
      name: proxmoxer
      state: present
  - name: Create new container automatically selecting the next available vmid.
    community.general.proxmox:
      node: 'proxmox2-smartlink'
      api_user: 'root@pam'
      api_password: "{{ proxmox_pass}}"
      api_host: 157.15.58.25
      password: "{{ proxmox_pass }}"
      hostname: "{{ container_hostname }}"
      ostemplate: 'local:ubuntu-24.04-standard_24.04-2_amd64.tar.zst'
    
