---
- name: Create and control containers on proxmox using Ascender
  hosts: proxmox_servers
  tasks:
  - name: Create new container automatically selecting the next available vmid.
  community.general.proxmox:
    api_user: 'root@pam'
    api_password: '1q2w3e'
    api_host: 'node1'
    password: '123456'
    hostname: 'example.org'
    ostemplate: 'local:vztmpl/ubuntu-14.04-x86_64.tar.gz'
