---
- hosts: proxmox_servers
  become: true
  vars:
    container_id: 105
    container_name: ubuntu24-lxc
    template_name: local:vztmpl/ubuntu-24.04-standard_24.04-1_amd64.tar.gz
    ip_address: 10.80.28.105/24
    gateway: 10.80.28.1
    root_password: "securepassword"  # Change to a secure password
    storage: local-lvm
    cores: 2
    memory: 2048  # Memory in MB
    disk_size: 10G  # Disk size in GB
  tasks:
  - name: Create LXC container
    community.general.proxmox_lxc:
      node: pve
      vmid: 101
      template: "local:vztmpl/ubuntu-24.04-standard_24.04-1_amd64.tar.gz"
      state: present
      ostype: ubuntu
      memory: 512
      net:
        - name: eth0
          bridge: vmbr0
          ip: 10.80.28.105/24
      gateway: 10.80.28.1

