---
- name: Update web servers
  hosts: proxmox_servers

  tasks:
  - name: Create new container automatically selecting the next available vmid.
    community.general.proxmox:
      node: 'uk-mc02'
      api_user: 'root@pam'
      api_password: '1q2w3e'
      api_host: 'node1'
      password: '123456'
      hostname: 'example.org'
      ostemplate: 'local:ubuntu-24.04-standard_24.04-2_amd64.tar.zst'
    
