---
- name: Update web servers
  hosts: proxmox_servers

  tasks:
  - name: Create new container automatically selecting the next available vmid.
    community.general.proxmox:
      node: 'proxmox'
      api_user: 'root@pam'
      api_password: 'TechCare@@2'
      api_host: '157.15.58.24'
      password: 'TechCare@@2'
      hostname: 'server1.merosoftnepal.com'
      ostemplate: 'local:ubuntu-24.04-standard_24.04-2_amd64.tar.zst'
    
